import marimo

__generated_with = "0.18.4"
app = marimo.App(width="medium")


@app.cell
def _(mo):
    mo.md(r"""
    # Generate Embeddings

    This is an example code of how embeddings are generated by a machine learing model.
    """)
    return


@app.cell
def _():
    # Initial imports
    import os

    import marimo as mo
    import numpy as np
    import pandas as pd

    from src.globals import CSV_FOLDER
    return CSV_FOLDER, mo, np, os, pd


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Load the dataset
    """)
    return


@app.cell
def _(CSV_FOLDER, os, pd):
    subpath = "LargeDataset"
    filename = "dataset_no_overlaps_260315_171700.csv"
    df = pd.read_csv(
        os.path.join(CSV_FOLDER, subpath, filename), index_col="track_id"
    )
    df
    return (df,)


@app.cell
def _(df):
    mask = (df.voice_quality == 3) & (~df.multiple_voices)
    df[mask]
    return (mask,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Generate Embeddings
    """)
    return


@app.cell
def _():
    import torchaudio
    from speechbrain.inference.encoders import MelSpectrogramEncoder

    encoder = MelSpectrogramEncoder.from_hparams(
        source="speechbrain/spkrec-ecapa-voxceleb-mel-spec"
    )
    return (encoder,)


@app.cell
def _():
    SAMPLE_RATE = 24_000
    return (SAMPLE_RATE,)


@app.cell
def _(SAMPLE_RATE, librosa, np, torch):
    def get_trimmed_audio(audiopath: str) -> torch.Tensor:
        """Returns an audio sample array, with the silent parts cut out

        Args:
            audiopath (str): The path to the audio file

        Returns:
            torch.tensor: The audio sample array
        """
        y, sr = librosa.load(audiopath, sr=SAMPLE_RATE, mono=True)
        intervals = librosa.effects.split(y)
        trimmed_parts = []
        for start, end in intervals:
            trimmed_parts.append(y[..., start:end])
        return torch.from_numpy(np.concatenate(trimmed_parts, axis=-1))
    return (get_trimmed_audio,)


@app.cell
def _(df, encoder, get_trimmed_audio, mask, np):
    # Generate the embeddings
    # 1. apply mask to the dataframe
    # 2. trim the audio file and get the sample array
    # 3. generate the embedding using the embedding model
    # 4. convert to a 3D numpy array.

    embeddings = np.stack(
        df[mask]
        .vocal_audio_path.apply(
            lambda path: encoder.encode_waveform(get_trimmed_audio(path))
            .cpu()
            .numpy()
            .squeeze()
        )
        .values
    )
    return


if __name__ == "__main__":
    app.run()
